### PR TITLE
Add token balances to utxo sum

### PR DESCRIPTION
**Pull request by pedromtcosta**
# Abstract
This PR intends to add the total token balances to the `/api/txs/utxoSumForAddresses`.

# Background
On Ergo Platform API `v0` we were using an endpoint which returns all transactions for the addresses to then sum the values of the UTxOs. In `v1` Ergo Platform adds a new endpoint which already returns the summed UTxOs ([getApiV1AddressesP1BalanceTotal](https://api.ergoplatform.com/api/v1/docs/#operation/getApiV1AddressesP1BalanceTotal)), so there's no need for us to do this calculation on our end anymore.

# Implementation
The implementation consists of changing the `getBalanceForAddress` to use the `getApiV1AddressesP1BalanceTotal` endpoint from Ergo Platform `v1`, which also includes the balances for the tokens. We then simply change the `utxoSumForAddresses` function to use the new data format returned by `getBalanceForAddress`.

The expected argument for this endpoint is an array of addresses and the previous implementation was was summing up the total ERG for all addresses. This behavior is being kept in the current implementation, taking into consideration the total balances for the tokens as well.

The new response includes the total ERG balance in a new field named `totalNanoErgs`, as well as in the old `sum` field for backward compatibility

### CODE REVIEW

**Comment by yushih** [comment]
Please update the API doc in README.

**Comment by vsubhuman** [comment]
@anon-br , plz review

**Comment by anon-br** [comment]
@pedromtcosta, the tests related to `utxoSumForAddresses` are't passing, can you please fix them?

**Comment by pedromtcosta** [comment]
> @pedromtcosta, the tests related to `utxoSumForAddresses` are't passing, can you please fix them?

Sorry about that, tests fixed!

**Review by vsubhuman — APPROVED** [review]

**Pull request merged**
